// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Content for Events documents
 */
interface EventsDocumentData {
  /**
   * Imagen field in *Events*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: events.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Título field in *Events*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: events.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Descripción field in *Events*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descripción del evento
   * - **API ID Path**: events.descripcion
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  descripcion: prismic.RichTextField;

  /**
   * Día field in *Events*
   *
   * - **Field Type**: Date
   * - **Placeholder**: Dia del evento
   * - **API ID Path**: events.day
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  day: prismic.DateField;

  /**
   * Hora field in *Events*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Horario del evento
   * - **API ID Path**: events.hour
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  hour: prismic.KeyTextField;

  /**
   * Hora de fin field in *Events*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Horario de finalización (opcional)
   * - **API ID Path**: events.hour_end
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  hour_end: prismic.KeyTextField;

  /**
   * Categoría field in *Events*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Categoría del evento
   * - **API ID Path**: events.categoria
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  categoria: prismic.KeyTextField;

  /**
   * Mas Info field in *Events*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Más info (Link)
   * - **API ID Path**: events.more
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  more: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Events document from Prismic
 *
 * - **API ID**: `events`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EventsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<EventsDocumentData>, "events", Lang>;

/**
 * Content for Link de Mercado Pago documents
 */
interface MpLinkDocumentData {
  /**
   * Link field in *Link de Mercado Pago*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link para pagar
   * - **API ID Path**: mp_link.link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Importe field in *Link de Mercado Pago*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: mp_link.importe
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  importe: prismic.NumberField;

  /**
   * Texto field in *Link de Mercado Pago*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mp_link.texto
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  texto: prismic.KeyTextField;

  /**
   * Tipo field in *Link de Mercado Pago*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Mensual
   * - **API ID Path**: mp_link.tipo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  tipo: prismic.SelectField<"Mensual" | "Anual" | "Unica", "filled">;
}

/**
 * Link de Mercado Pago document from Prismic
 *
 * - **API ID**: `mp_link`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MpLinkDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<MpLinkDocumentData>, "mp_link", Lang>;

type PageDocumentDataSlicesSlice = EventSlice | RichTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Content for Parrafo documents
 */
interface ParagraphDocumentData {
  /**
   * Texto field in *Parrafo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Texto
   * - **API ID Path**: paragraph.text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;

  /**
   * Color field in *Parrafo*
   *
   * - **Field Type**: Color
   * - **Placeholder**: Color
   * - **API ID Path**: paragraph.color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  color: prismic.ColorField;

  /**
   * Tamaño de fuente field in *Parrafo*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Tamaño de fuente
   * - **API ID Path**: paragraph.font_size
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  font_size: prismic.NumberField;
}

/**
 * Parrafo document from Prismic
 *
 * - **API ID**: `paragraph`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ParagraphDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ParagraphDocumentData>,
    "paragraph",
    Lang
  >;

export type AllDocumentTypes =
  | EventsDocument
  | MpLinkDocument
  | PageDocument
  | ParagraphDocument;

/**
 * Primary content in *Event → Default → Primary*
 */
export interface EventSliceDefaultPrimary {
  /**
   * Titulo field in *Event → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Descripción field in *Event → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descripción del evento
   * - **API ID Path**: event.default.primary.descripcion
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  descripcion: prismic.RichTextField;

  /**
   * Imagen field in *Event → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: event.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Día field in *Event → Default → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: Día del evento
   * - **API ID Path**: event.default.primary.day
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  day: prismic.DateField;

  /**
   * Hora field in *Event → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Horario del evento
   * - **API ID Path**: event.default.primary.hour
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  hour: prismic.KeyTextField;

  /**
   * Hora de fin field in *Event → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Horario de finalización (opcional)
   * - **API ID Path**: event.default.primary.hour_end
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  hour_end: prismic.KeyTextField;

  /**
   * Categoría field in *Event → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Categoría del evento
   * - **API ID Path**: event.default.primary.categoria
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  categoria: prismic.KeyTextField;

  /**
   * Más info field in *Event → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Más info (Link)
   * - **API ID Path**: event.default.primary.more
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  more: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for Event Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EventSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EventSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Event → with children → Primary*
 */
export interface EventSliceWithChildrenPrimary {
  /**
   * Titulo field in *Event → with children → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event.withChildren.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Imagen field in *Event → with children → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: event.withChildren.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * with children variation for Event Slice
 *
 * - **API ID**: `withChildren`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EventSliceWithChildren = prismic.SharedSliceVariation<
  "withChildren",
  Simplify<EventSliceWithChildrenPrimary>,
  never
>;

/**
 * Slice variation for *Event*
 */
type EventSliceVariation = EventSliceDefault | EventSliceWithChildren;

/**
 * Event Shared Slice
 *
 * - **API ID**: `event`
 * - **Description**: Event
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EventSlice = prismic.SharedSlice<"event", EventSliceVariation>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      EventsDocument,
      EventsDocumentData,
      MpLinkDocument,
      MpLinkDocumentData,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      ParagraphDocument,
      ParagraphDocumentData,
      AllDocumentTypes,
      EventSlice,
      EventSliceDefaultPrimary,
      EventSliceWithChildrenPrimary,
      EventSliceVariation,
      EventSliceDefault,
      EventSliceWithChildren,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
    };
  }
}
