// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  event: dynamic(() => import("./Event")),
  rich_text: dynamic(() => import("./RichText")),
};
